### PR TITLE
fixed logic error in annotator/views.py get_states for issue135

### PR DESCRIPTION
**Pull request by clayshieh**
fixes logic error for issue #135 where if condition is based on a potentially None value which leads to a runtime error.

### CODE REVIEW

**Comment by clayshieh** [comment]
also shortened for loop to an equivalent list comprehension

**Comment by antingshen** [comment]
What was the issue? The code looks identical in function though I may be missing something

**Comment by clayshieh** [comment]
The original code had a logic error where the variable name `label_name` was only being instantiated and assigned a value if it was in the request GET header. For existing instances or other cases if the front end makes the same request without the label_name in the request header then you’d end up with the same error in the issue because `label_name` was never instantiated. So fix is to just assign `label_name` to the value of the `.get` method because that returns a default value of None if its not in the header and the filter will work as expected with no runtime error. This also implies that the front end js app is missing an if condition too before making the call to this end point, ill check/fix that in another pr.

**Comment by antingshen** [comment]
Oh yes that makes sense. Looks good to me

**Pull request merged**
