### PR TITLE
Customised turk admin

### PR DESCRIPTION
**Pull request by alex-birch**
Hi,

We've gone ahead and added Mechanical Turk support to the admin interface as well as a bit of workflow.

Some comments:
- you can now accept/reject turk work straight from the videos page
- available statuses are: Not Published, Published, Awaiting Approval, Verified

Here are some screenshots:

image

image

image

TODO - add in some help instructions to the Readme into publishing to turk.

Quick summary here:

make sure you've configured deploy_settings.py with amazon turk user key and secret key

1. go to the videos admin view
2. select the videos you want to publish to turk
3. select actions->publish to turk

### CODE REVIEW

**Comment by alex-birch** [comment]
Hi,

I've enhanced this further:
1. you can now approve/reject locally without having turk integration
2. when a turk worker submits to beaver, you can directly e-mail them from video. Please see screenshot. This is so you don't have to reject the workers straight away (they get pretty upset if you reject them we found!)
3. you now see the status up the top right of the video at all times
4. when you hit reject, the annotations are updated if you made any changes

image

image

image

**Comment by antingshen** [comment]
Ah yes, we found that it's best to always accept worker's work but not allow them to do more work unless they improve their quality

**Comment by alex-birch** [comment]
Following on from your comment, you can now republish to a new hit, and optionally block the worker from the accept form as well as from the reject form

**Comment by antingshen** [comment]
Thanks!

**Comment by clayshieh** [comment]
~admin "publish to turk" is not working properly when Debug = False~

nevermind, looks like it's not a result of these functions. It seems to be a problem with admin as a whole.

**Comment by alex-birch** [comment]
Can you please give a bit more info?

This works for me under Apache 2 with Debug false and ALLOWED_HOSTS set


Thanks,

**Pull request merged**
