### PR TITLE
preload fix for issue 105

### PR DESCRIPTION
**Pull request by clayshieh**

### CODE REVIEW

**Comment by antingshen** [comment]
I wonder if it's better to implement streaming, or at least make this optional, or only when seeking otherwise fails (similar to how firefox handles it). Do you know how difficult these other alternatives would be?

One of the assumptions on BeaverDam workflow is that a worker will start from the beginning of the video, and by the time they get to later parts of the video, it should be loaded. This avoids them loading the entire video file to start, which may slow them down.

**Comment by clayshieh** [comment]
It seems like most web servers support byte serving by default already but its not something django runserver itself supports. Haven't tried it but its most likely not a problem in production mode/setting.

**Comment by clayshieh** [comment]
Alternatively you could also just install whitenoise's middleware to serve media when testing in non production mode to solve the problem.

**Comment by antingshen** [comment]
Perhaps we should make it so that if the webserver doesn't support it, we'll pre-load, but default to assuming the webserver supports it since otherwise the user will have to wait a long time before starting

**Pull request closed without merging**
