### PR TITLE
Added similar color for same object

### PR DESCRIPTION
**Pull request by allenywang**
For Issue #42. All objects of the same type will have similar colors. Defaulted to be red, blue, and green to allow clear distinction between objects. More colors are listed in case more object types are added.

### CODE REVIEW

**Comment by antingshen** [comment]
Would it be easier to just hard code in 25 colors per type?

**Comment by antingshen** [comment]
Actually, how does it look if we just use a single color for all instances of a type?

**Comment by allenywang** [comment]
It looks fine for frames with less objects, but I don't think it's ideal if you have a lot of the same objects cramped together. Hard coding it is fine too if you'd prefer that.

**Comment by antingshen** [comment]
Nope this looks fine to me. Do you think we should use these colors for the radio buttons for the types too?

**Comment by allenywang** [comment]
Yeah, we should change the radio buttons colors too. Alright, so just hard code the colors then?

**Comment by antingshen** [comment]
Ok! I think maybe 10 per type is good enough for now.

**Pull request merged**
