### PR TITLE
Img list ux fixes

### PR DESCRIPTION
**Pull request by lukemurray**
This
- Makes buffering in the imgplay plugin a little smarter
- Adds loading feedback for the imgplayer if you jump frames to an un-buffered time

Question, if the video is larger than the viewport (browser) was it previously scaling it down (and the SVG) or leaving it fullsize?

### CODE REVIEW

**Comment by antingshen** [comment]
It was previously scaling it down to fit the viewport

**Comment by lukemurray** [comment]
OK, it is still scaling the video down. but not the SVG. I think our previous PR broke that (not this one), sorry.

We'll look into that and submit another PR.

**Comment by antingshen** [comment]
No worries :) Shall I merge this one?

**Comment by lukemurray** [comment]
Yes this one fixes a bunch of things for the image sequences

**Pull request merged**
