### PR TITLE
Fix email views

### PR DESCRIPTION
**Pull request by msis**
Not all email views require `reopen`, etc.
Fixed using the same philosophy.

### CODE REVIEW

**Comment by antingshen** [comment]
From reading the code, it looks like it'll still throw and catch an exception when there's no `reopen` etc?

**Comment by msis** [comment]
Not exactly, `reopen` and the rest are automatically populated by the default values if they're prompted.
But over the long term, and to allow for more flexibility, I believe we should maybe move the `if` statements to line 234 (my commit, or 230 original file). That way, only when the command is know, the verification happens.
Right now, without this fix, an error occurs.

**Comment by antingshen** [comment]
Ah I see. Makes sense. Yes maybe we should move the verification to after command is known, but this is indeed an improvement vs before.

**Comment by msis** [comment]
In the last commit I just call `data` directly from the function avoiding the if statement.

**Comment by antingshen** [comment]
Looks good, thank you!

**Pull request merged**
